INSERT INTO USER("ID", "EMAIL" , "FIRSTNAME" , "LASTNAME", "PASSWORD") VALUES (1, 'dennis@pannek.eu', 'Dennis', 'LOEPKE', 'test123')
INSERT INTO ROLES("ID", "ROLE") VALUES (1, 'admin')
INSERT INTO USER_ROLES("USER_ID", "ROLES_ID") VALUES (1, 1)